### ISSUE TITLE
Issue with flashing ESP32-S3 with flowcode10

### ISSUE THREAD

**Issue by Bentlybro** [RowlandTechnology/CapTouchDisplay#1]
Hey here is the logs and some of my setup

![image](https://github.com/RowlandTechnology/CapTouchDisplay/assets/27962737/b30d7757-9a0e-4263-beb0-34216aca2008)

Here are the logs, It fails so close to the end

[error.txt](https://github.com/RowlandTechnology/CapTouchDisplay/files/14345402/error.txt)

**Comment by RowlandTechnology** [comment]
Hello,

Many thanks for letting me know. When you have opened the example haveyou downloaded the entire project along with the images folder? I wonder if the BitmapDrawer component is simply missing its images.

You can see them here in the properties of the BitmapDrawer1 component.
![image](https://github.com/RowlandTechnology/CapTouchDisplay/assets/21124591/5483ea32-57bf-41f0-a117-d8d3dee6ddcf)

**Comment by RowlandTechnology** [comment]
Project file should look like this with an images folder.
![image](https://github.com/RowlandTechnology/CapTouchDisplay/assets/21124591/08803fd0-bcdb-4992-bc32-12e30ed65b5c)

**Comment by RowlandTechnology** [comment]
Just in case this isn't the issue I've also pushed an update to the Bitmap Drawer component to force the value of the colour depth to remove the compiler error.

**Comment by Bentlybro** [comment]
![image](https://github.com/RowlandTechnology/CapTouchDisplay/assets/27962737/0ca262ac-50dc-43ff-bbf9-f29e5be9ada6)

This is whats there in flowcode and the files i have downloaded look like this 
![image](https://github.com/RowlandTechnology/CapTouchDisplay/assets/27962737/dfc4967a-1d85-48eb-a2d5-cf6e2ccc6dd5)
so i am missing a file it seems?

**Comment by RowlandTechnology** [comment]
That looks ok, please try the help -> library updates again and hopefully the update should solve the compile error.

**Comment by Bentlybro** [comment]
Yeah i saw the update and i got that, building and writing to the screen now... And that worked! i now have the default test script back on the screen and its properly working, thank you so much for all the help!

**Comment by Bentlybro** [comment]
so it mentions the wifi creds is not set which is true, how would i go about setting those as at the moment its getting that from "eeprom1" which is not set yet

**Comment by RowlandTechnology** [comment]
Aha yes when the wifi is unconnected it should host it's own unsecured network that you can connect to. If you then visit the URL 192.168.4.1 then you will be able to provide your local network login details.

**Comment by Bentlybro** [comment]
i dont see that in the base script?, that may need looking at but i have it working, now to try strip it back down to its bare basic script to work on it with, thank you for all the help you have provided with everything, i think i should be good to go from here now, if i have any more issues or questions ill let you know

**Comment by RowlandTechnology** [comment]
Aha sorry I've now updated the example with more functionality including the wifi connect routine using the webserver and the clock option to show the current time and date. More to come soon.

**Comment by Bentlybro** [comment]
sweet thank you, ill give it a go and see how well it works 🚀

**Comment by Bentlybro** [comment]
so it does start its own hotspot to add the wifi SSID and password, but when i set them correctly it keeps failing to connect for some reason, the SSID and password is set where correct as i see the correct SSID on startup - can we add a debug option to show why it failed? like wrong password or timeout ect,  - the reason it was failing is the EEPROM1 had the wrong password set so i had to get around that as the webui did not update it that properly, also is there a way to setup a keyboard on the screen for user text input? i basically want to try make this into a system where i can send messages from the screen to my servers api and show the reply message, do you think this will be possible

**Comment by RowlandTechnology** [comment]
A full on screen keyboard is probably doable but might be tricky to do well. Having a reduced cut down number of keys or even key words / commands you use all the time might be easier. Another option might be to look at support for a Bluetooth keyboard as the ESP module has Bluetooth capabilities. I would need to look at supporting this in Flowcode if this were the path you wanted to take.

**Comment by Bentlybro** [comment]
hmm alright ill see what i can do, ill be honest im new to flowcode so i am just doing a lot of testing and getting to just of what can be done with it but it does seem pretty powerful, from the way i have seen how everything is setup, i would have to draw a touch area, then a box then the letter for every key so that's 26 x 3 steps just to draw the keyboard if im correct and nothing else? seems complicated but doable for sure, im trying to avoid a physical keyboard if possible as i am trying to make a all in one device for my AI system that i am working on - i was wondering if we could possibly use [squareline studio](https://squareline.io) to program the screen? as it has Arduino with TFT_eSPI in it? not sure if the current screen uses that but its something
